theme: jekyll-theme-minimal
title: CASIRAGHIAPP
description: Casiraghiani, ecco a voi l'app del Liceo, da ora disponibile anche su PC!
github:
  is_project_page: false
show_downloads: false
logo: https://drive.google.com/file/d/1cQriDAbYPR9Wa8jcet9h6mxy_qn8d60L/view?usp=sharing
